// TODO extend
enum demi_type {
    DEMI_TYPE_UNKNOWN = 1,
    DEMI_TYPE_MOUSE,
    DEMI_TYPE_TABLET,
    DEMI_TYPE_TOUCHPAD,
    DEMI_TYPE_KEYBOARD,
    DEMI_TYPE_JOYSTICK,
    DEMI_TYPE_TOUCHSCREEN,
    DEMI_TYPE_SWITCH,
    DEMI_TYPE_ACCELEROMETER,
    DEMI_TYPE_POINTING_STICK,
    DEMI_TYPE_BOOT_VGA,
};

// TODO extend
enum demi_class {
    DEMI_CLASS_UNKNOWN = 1,
    DEMI_CLASS_DRM,
    DEMI_CLASS_INPUT,
};

enum demi_action {
    DEMI_ACTION_UNKNOWN = 1,
    DEMI_ACTION_ATTACH,
    DEMI_ACTION_DETACH,
    DEMI_ACTION_CHANGE,
    // DEMI_ACTION_HOTPLUG,
    // DEMI_ACTION_LEASE,
};
